version: '3.0'

services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "80:80"
    env_file:
      - ./.env
    restart: "always"
    volumes:
      - .:/home
      - ./storage:/storage
