FROM python:3.7

WORKDIR /home

# django docker environment
RUN apt-get update

# node docker environment
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
ENV NODE_VERSION 12.18.0
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y aptitude nodejs
RUN npm install -g @vue/cli

# default
VOLUME ["/home"]
COPY . .

RUN rm -f package-lock.json && npm install
RUN chmod +x /home/entrypoint_front.sh

EXPOSE 8080
EXPOSE 8000
ENTRYPOINT [ "/home/entrypoint_front.sh" ]