FROM python:3.7

WORKDIR /home

# django docker environment
RUN apt-get update
COPY requirements.txt /home/requirements.txt
RUN pip install -r requirements.txt
RUN git clone https://github.com/arteria/django-background-tasks.git \
    && cd django-background-tasks && pip install -r requirements.txt && python setup.py install

RUN python -c "import nltk; nltk.download('brown'); nltk.download('stopwords'); nltk.download('punkt'); nltk.download('wordnet'); nltk.download('averaged_perceptron_tagger')"
RUN python -m spacy download en_core_web_sm

VOLUME ["/home"]
COPY . .

RUN npm install
RUN chmod +x /home/entrypoint_back.sh

EXPOSE 2300
ENTRYPOINT [ "/home/entrypoint_back.sh" ]