version: '3.0'

services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "80:80"
      - "8000:8000"
    environment: 
      - ROOT=$ROOT
      # - WATCH=$WATCH
    env_file:
      - ./.env
    restart: "always"
    volumes:
      - .:/home
      - $ROOT:/storage
      # - $WATCH:/watch
